### ISSUE TITLE
팀원 구함 or 팀 구함

### ISSUE THREAD

**Issue by jyheo** [cse-hansung/capstone2022#1]
# 아래 내용은 예시입니다. 꼭 이렇게 써야 한다는 것은 아닙니다. 연락은 github을 통해 연락하세요.

# 부족한 팀원을 구함(현재 팀원 2, 3명인 팀)
 - 희망 주제 분야, 스터디 계획(어떤것을 공부할 것인지)
 - 팀원이 갖췄으면 하는 최소한의 스킬, 너무 많이 쓰거나 학과에서 배우지 않는 내용을 요구하지는 말것.

# 혼자인 사람이 팀을 구하거나 팀을 새로 만들려고 할 때
 - 희망 주제 분야
 - 가능한 개발 스킬(C, C++, Java, 파이썬, SQL, 코틀린, 안드로이드 앱, 스프링, nodejs, django, bootstrap, Unity3D, Unreal...)

**Comment by isyslab-admin** [comment]
팀원이 되고 싶습니다. 저는 이런거 이런거 할 줄 압니다.

**Comment by jyheo** [comment]
@isyslab-admin 연락 바랍니다.

> 팀원이 되고 싶습니다. 저는 이런거 이런거 할 줄 압니다.

**Comment by isyslab-admin** [comment]
제 연락처는 XXX 입니다. 연락 바랍니다.
 
-----Original Message-----
